apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
    {{- include "sso.labels" $ | nindent 4 }}
data:
  SSO_SITE_NAME: {{ .Values.siteName | quote }}
  SERVER_EMAIL: {{ .Values.serverEmail | quote }}
  SSO_DOMAIN: {{ .Values.domain | quote }}
  DATABASE_HOST: {{ .Values.databaseHost | default (printf "%s-postgresql" .Release.Name ) }}
  DATABASE_NAME: {{ .Values.global.postgresql.auth.database }}
  DATABASE_USER: {{ .Values.global.postgresql.auth.username}}
  {{- if .Values.memcached.enabled }}
  CACHES_LOCATION: {{ .Release.Name }}-memcached:11211
  {{- end }}
