apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "sso.labels" $ | nindent 4 }}
type: Opaque
stringData:
  DATABASE_PASSWORD: {{ .Values.global.postgresql.auth.password }}
  SECRET_KEY: {{ .Values.secretKey }}
  {{- if .Values.celeryBrokerURL }}
  CELERY_BROKER_URL: {{ .Values.celeryBrokerURL}}
  {{- end }}
  RECAPTCHA_PRIVATE_KEY: {{ .Values.recaptchaPrivateKey | quote}}
  SSO_GOOGLE_GEO_API_KEY: {{ .Values.ssoGoogleGeoApiKey | quote}}
