apiVersion: v2
name: keycloak
description: A Helm chart for Kubernetes

type: application
version: 1.1.3
appVersion: "1.16.0"

dependencies:
  - name: keycloakx
    version: 1.7.0
    repository: "@codecentric"
    condition: keycloakx.enabled
    tags:
      - keycloakx
  - name: postgresql
    version: 11.9.13
    repository: "@bitnami"
    condition: postgresql.enabled
    tags:
      - postgresql
