{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "django-app.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "django-app.selectorLabels" . | nindent 6 }}
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
{{- end -}}
