apiVersion: v2
name: django-app
description: A Helm chart for Kubernetes
type: application
version: 1.0.1
appVersion: "2.0.4"
dependencies:
  - name: postgresql
    version: 12.1.3
    repository: "@bitnami"
    condition: postgresql.enabled
    tags:
      - postgresql
