{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sso.fullname" . }}-backend
  labels:
    {{- include "sso.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "sso.fullname" . }}-backend
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- toYaml .Values.autoscaling.metrics | nindent 4 }}
  behavior:
    {{- toYaml .Values.autoscaling.behavior | nindent 4 }}
{{- end }}
{{- if .Values.messaging.autoscaling.enabled }}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sso.fullname" . }}-messaging
  labels:
    {{- include "sso.labelsMessaging" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "sso.fullname" . }}-messaging
  minReplicas: {{ .Values.messaging.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.messaging.autoscaling.maxReplicas }}
  metrics:
    {{- toYaml .Values.messaging.autoscaling.metrics | nindent 4 }}
  behavior:
    {{- toYaml .Values.messaging.autoscaling.behavior | nindent 4 }}
{{- end }}
{{- if .Values.media.autoscaling.enabled }}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sso.fullname" . }}-media
  labels:
    {{- include "sso.labelsMedia" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "sso.fullname" . }}-media
  minReplicas: {{ .Values.media.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.media.autoscaling.maxReplicas }}
  metrics:
    {{- toYaml .Values.media.autoscaling.metrics | nindent 4 }}
  behavior:
    {{- toYaml .Values.media.autoscaling.behavior | nindent 4 }}
{{- end }}
